import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider";
import { ProviderSesion } from "./providers";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/_components/home/navbar/Navbar";
import FooterSection from "@/_components/home/footer/FooterSection";
import LayoutWrapper from "./layout-wrapper";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.className}`}>
        <Provider>
          <ProviderSesion>
            <LayoutWrapper>{children}</LayoutWrapper>
          </ProviderSesion>
        </Provider>
      </body>
    </html>
  );
}
